# Generated by Django 6.1.1 on 2026-09-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
