# Generated by Django 6.1.1 on 2026-10-06 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='FREE', max_length=10)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
